# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f046b77d8e939da5232e30dab32ee3eebe35913f09c246dfe91bd8b395f71f3e5b3587efdeb78540b0fc0f574b2a90b02322b5f35514f86204bc640ff3921c4

test:
  secret_key_base: 6665add6109df71eafb07954b6e3dc626dab61e41c13b8b8e01308449a6fc73497d1be231dce3547b8d9bc9eb59890f0ab1ea7089a7ba1e162f14d4c15c21d4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
